name = "Bob"

[model]
api = "ollama"
# model = "Sweaterdog/Andy-4:q8_0"
model = "qwen3.5:27b"
url = "https://ollama-melchior.arc.upiscium.dev"

[embedding]
api = "ollama"
model = "embeddinggemma:latest"
url = "https://ollama.arc.upiscium.dev"
