name = "Bob"

[model]
api = "ollama"
model = "gemma4:26b"
url = "https://ollama-caspar.arc.upiscium.dev"

[embedding]
api = "ollama"
model = "embeddinggemma:latest"
url = "https://ollama-balthazar.arc.upiscium.dev"

